import { test } from 'node:test';
import assert from 'node:assert/strict';
import { buildAutoGeneratedRobots } from '../src/integration/index.ts';

const SITE = 'https://example.com';

test('robots: the Sitemap line is only written when @astrojs/sitemap is configured', () => {
  // Found in production: robots.txt pointed search engines at
  // /sitemap-index.xml on a site that had no sitemap integration, so the URL
  // it advertised was a 404.
  assert.match(buildAutoGeneratedRobots(SITE, true, true), /Sitemap: https:\/\/example\.com\/sitemap-index\.xml/);
  assert.doesNotMatch(buildAutoGeneratedRobots(SITE, true, false), /Sitemap:/);
});

test('robots: a trailing slash on the site URL does not double up', () => {
  assert.match(buildAutoGeneratedRobots(SITE + '/', true, true), /Sitemap: https:\/\/example\.com\/sitemap-index\.xml$/m);
});

test('robots: no site URL, no Sitemap line, even with the integration', () => {
  assert.doesNotMatch(buildAutoGeneratedRobots('', true, true), /Sitemap:/);
});

test('robots: allowAICrawlers=false adds the AI crawler block; true leaves it out', () => {
  const blocked = buildAutoGeneratedRobots(SITE, false, false);
  assert.match(blocked, /User-agent: GPTBot\nDisallow: \//);
  assert.match(blocked, /User-agent: ClaudeBot\nDisallow: \//);
  assert.doesNotMatch(buildAutoGeneratedRobots(SITE, true, false), /GPTBot/);
});
