import type { ResolvedRegistry } from '../types.js';
import { extractTemplateKey, extractWidgetKey } from './shared.js';

/**
 * `parche.d.ts`, injected into the site's own types (Astro's `injectTypes`):
 * what this site's parches provide, as unions a site's TypeScript can name —
 * a custom route picking a widget by key, a script naming a locale or a
 * theme. Written again on every start, from the registry; never edited.
 */
export function generateTypesDeclaration(registry: ResolvedRegistry): string {
  const union = (values: string[]) => (values.length ? [...new Set(values)].sort().map((v) => JSON.stringify(v)).join(' | ') : 'never');
  const ids = Object.keys(registry.modules);
  const widgets = ids.filter((id) => id.startsWith('parche:widgets/')).map(extractWidgetKey);
  const templates = ids.filter((id) => id.startsWith('parche:templates/')).map(extractTemplateKey);
  return `// Generated by @parche/astro from the parches this site imports, on every start. Do not edit.
declare namespace Parche {
  /** The widgets this site can render, by key: the \`widget\` of a node. */
  type Widget = ${union(widgets)};
  /** The templates the apps register, by name. */
  type Template = ${union(templates)};
  /** The elements the parches provide, by name. */
  type Element = ${union(Object.keys(registry.elements))};
  /** The site's locales. */
  type Locale = ${union(registry.i18n.locales)};
  /** The themes available; \`""\` is the base look. */
  type Theme = ${union(registry.themes.map((t) => t.value))};
  /** The apps: parches with routes, a resolver or options of their own. */
  type App = ${union(registry.apps.map((a) => a.name))};
}
`;
}
