import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

/** What a build writes into robots.txt after this marker; a site's own lines before it are kept. */
const ROBOTS_MARKER = '# === PARCHE:AUTO-GENERATED';

export function processRobotsTxt(outDir: URL, siteUrl: string, allowAICrawlers: boolean, hasSitemap: boolean) {
  const robotsPath = path.join(fileURLToPath(outDir), 'robots.txt');
  // Also check the static client dir for SSR builds
  const clientDir = path.join(fileURLToPath(outDir), 'client');
  const robotsClientPath = fs.existsSync(clientDir)
    ? path.join(clientDir, 'robots.txt')
    : null;

  const targetPath = fs.existsSync(robotsPath)
    ? robotsPath
    : robotsClientPath && fs.existsSync(robotsClientPath)
      ? robotsClientPath
      : null;

  const generated = buildAutoGeneratedRobots(siteUrl, allowAICrawlers, hasSitemap);

  if (targetPath) {
    const content = fs.readFileSync(targetPath, 'utf-8');
    const markerIdx = content.indexOf(ROBOTS_MARKER);
    if (markerIdx !== -1) {
      // Replace everything from the marker onwards
      const before = content.slice(0, markerIdx);
      fs.writeFileSync(targetPath, before + ROBOTS_MARKER + '\n' + generated, 'utf-8');
    }
    // If no marker, don't touch the file — user has full control
  } else {
    // No robots.txt exists — generate a complete one
    const outPath = robotsClientPath
      ? path.join(clientDir, 'robots.txt')
      : robotsPath;
    const fullContent = `User-agent: *\nAllow: /\n\n${ROBOTS_MARKER}\n${generated}`;
    fs.writeFileSync(outPath, fullContent, 'utf-8');
  }
}

/**
 * The block after the marker in robots.txt. The Sitemap line is emitted only
 * when `@astrojs/sitemap` is configured: announcing /sitemap-index.xml to
 * search engines when nothing writes it is a 404 with a promise attached.
 */
export function buildAutoGeneratedRobots(
  siteUrl: string,
  allowAICrawlers: boolean,
  hasSitemap: boolean,
): string {
  const lines: string[] = [];

  if (!allowAICrawlers) {
    lines.push(
      '',
      '# AI Crawlers',
      'User-agent: GPTBot',
      'Disallow: /',
      '',
      'User-agent: Google-Extended',
      'Disallow: /',
      '',
      'User-agent: CCBot',
      'Disallow: /',
      '',
      'User-agent: anthropic-ai',
      'Disallow: /',
      '',
      'User-agent: ClaudeBot',
      'Disallow: /',
    );
  }

  if (siteUrl && hasSitemap) {
    lines.push('', `Sitemap: ${siteUrl.replace(/\/$/, '')}/sitemap-index.xml`);
  }

  return lines.join('\n');
}
